language: generic

sudo: required

services: 
  - docker

before_install:
  - echo "start Creating an image with docker"
  - docker build -t dudcke/react -f Dockerfile.dev

script:
  - docker run -e CI=true dudckd/react npm run test -- --coverage
  