language: generic

sudo: required

services: 
  - docker

before_install:
  - echo "start Creating an image with docker"
  - docker build -t dudckd/react -f Dockerfile.dev .

script:
  - docker run -e CI=true dudckd/react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: ap-northeast-2
  app: test
  env: Test-env
  bucket_name: elasticbeanstalk-ap-northeast-2-840213432037
  bucket_path: test
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SCREAT_ACCESS_KEY